language: php
php:
    - 5.5
    - 5.4
    - 5.3
install:
    - composer install
script: php bin/phing -propertyfile travis.properties build-travis
cache:
    directories:
        - vendor
        - build/magento
