language: php
php:
    - 5.5
    - 5.4
    - 5.3
install:
    - composer install
before_script:
    - mysql -e 'create database magento;'
    - php bin/n98-magerun install --dbHost="127.0.0.1" --dbUser="travis" --dbPass="" --dbName="magento" --installSampleData=yes --useDefaultConfigParams=yes --magentoVersion="1.9.0.1" --installationFolder="build/magento" --baseUrl="http://www.localhost.com:8080" -n
script: php bin/phing
